version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      xunit:
        patterns:
          - "xunit.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
