#!/usr/bin/env bash
set -euo pipefail

echo "${0##*/}": Formatting...
dotnet format --verify-no-changes

echo "${0##*/}": Building...
dotnet build --configuration Release --nologo

echo "${0##*/}": Testing...
dotnet test --configuration Release --no-build --nologo "${1:-}" "${2:-}"
