<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../fixtures/Fixtures.Cli/Fixtures.Cli.csproj" />
    <ProjectReference Include="../../fixtures/Fixtures.Xunit/Fixtures.Xunit.csproj" />
    <ProjectReference Include="../../src/SimpleExec/SimpleExec.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" />
  </ItemGroup>

  <ItemGroup>
    <None Update="hello-world.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
