<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../fixtures/Fixtures.Cli/Fixtures.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="hello-world.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="PublicApi.*.verified.txt">
      <DependentUpon>PublicApi.cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
