name: infer-sharp
on:
  push:
    branches: [main, release-*]
  pull_request:
permissions:
  security-events: write
jobs:
  infer-sharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.202'
      - uses: actions/checkout@v5.0.0
      - run: dotnet build
      - run: ls -al
      - run: pwd
      - uses: microsoft/infersharpaction@v1.5
        with:
          binary-path: './SimpleExec'
      - run: cat infer-out/report.txt
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: InferSharp reports
          path: infer-out/report.*
      - uses: github/codeql-action/upload-sarif@v3.23.0
        with:
          sarif_file: infer-out/report.sarif
