name: lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: github/super-linter@v4.9.0
        env:
          FILTER_REGEX_EXCLUDE: \bcodeql-analysis\.yml$|\bLICENSE$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
