name: lint
on:
  push:
    branches: [main, release-*]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: github/super-linter@v5.0.0
        env:
          FILTER_REGEX_EXCLUDE: \bcodeql-analysis\.yml$|\bLICENSE$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
