name: release
on:
  push:
    tags: ["*.*.*"]
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: 6.0.400
      - uses: actions/checkout@v3.0.2
      - run: dotnet build --configuration Release --nologo
      - name: push
        env:
          SOURCE: ${{ secrets.NUGET_PUSH_SOURCE }}
          API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
        if: env.SOURCE != '' || env.API_KEY != ''
        run: dotnet nuget push ./**/*.nupkg --source ${{ env.SOURCE }} --api-key ${{ env.API_KEY }}
