name: release
on:
  push:
    tags: ["*.*.*"]
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.200
      - uses: actions/checkout@v3.0.0
      - run: dotnet build --configuration Release --nologo
      - name: push
        env:
          API_KEY: ${{ secrets.RELEASE_NUGET_API_KEY }}
          SOURCE: ${{ secrets.RELEASE_NUGET_SOURCE }}
        if: ${{ env.API_KEY != '' || env.SOURCE != '' }}
        run: dotnet nuget push ./**/*.nupkg --source ${{ env.SOURCE }} --api-key ${{ env.API_KEY }}
